name: Connect to EC2 Instance

on:
  push:
    branches:
      - main  # Adjust the branch as per your requirement

jobs:
  connect_to_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display repository contents
        run: |
          echo "Displaying repository contents..."
          ls -R

      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.130.235.8 >> ~/.ssh/known_hosts

      - name: Connect to EC2 Instance and run command
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@18.130.235.8 'ls -la'
