name: Install Django Application

on:
  push:
    branches:
      - main  # Adjust the branch as per your requirement

jobs:
  install_django:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display repository contents
        run: |
          echo "Displaying repository contents..."
          ls -R

      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.130.235.8 >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./Ansible/installDjangoapp.yaml
          key: ${{ secrets.SSH_KEY }}
          inventory: |
            [my_ec2_instances]
            18.130.235.8 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa
          known_hosts: |
            18.130.235.8 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          options: |
            --verbose
        env:
          AWS_DEFAULT_REGION: eu-west-2
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
