name: Test Terraform

on:
  push:
    branches:
      - main  # Adjust the branch as per your requirement-tttt

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display repository contents-check
        run: |
          echo "Displaying repository contents..."
          ls -R
 
 
 
      - name: Generate Ansible Inventory
        run: |
          echo "[my_ec2_instances]" > ./Ansible/ansible_inventory.ini
          echo "10.0.1.1 ansible_user=ec2-user ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa" >> ./Ansible/ansible_inventory.ini
    
      - name: Display Ansible Ini
        run: |
          echo "Contents of Ansible Inventory:"
          cat ./Ansible/ansible_inventory.ini    

      - name: Display Contents in Ansible Folder
        run: |
            ls ./Ansible
               
      - name: Display pem file
        run: |
            cat ./Ansible/access_to_ec2.pem
                   
      - name: Display ansible_inventory.ini
        run: |
            cat ./Ansible/ansible_inventory.ini
                       
      - name: Display ansible playbook
        run: |
            cat ./Ansible/installDjangoapp.yaml
                                                  
 