name: Connect to EC2 Instance

on:
  push:
    branches:
      - main  # Adjust the branch as per your requirement

jobs:
  connect_to_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display repository contents
        run: |
          echo "Displaying repository contents..."
          ls -R

      - name: Check if Ansible is installed
        id: check_ansible
        run: |
          if command -v ansible >/dev/null 2>&1; then
            echo "Ansible is installed."
            echo "::set-output name=ansible_installed::true"
            ansible --version
          else
            echo "Ansible is not installed."
            echo "::set-output name=ansible_installed::false"
            exit 1
          fi

      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.130.237.32 >> ~/.ssh/known_hosts

      - name: Update Ansible inventory with public IP
        run: |
          echo "[my_ec2_instances]" > ./Ansible/ansible_inventory.ini
          echo "18.130.237.32 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ./Ansible/ansible_inventory.ini

      - name: Connect to EC2 Instance and run command
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@18.130.237.32 'ls -la'
        if: success() # Only run if previous step succeeded

      - name: Run Ansible playbook
        if: steps.check_ansible.outputs.ansible_installed == 'true'
        run: |
          ansible-playbook -i ./Ansible/ansible_inventory.ini ./Ansible/installDjangoapp.yaml --private-key ~/.ssh/id_rsa -u ec2-user -vvv
        env:
          AWS_DEFAULT_REGION: eu-west-2
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
